services:
  db:
    image: postgres:latest
    container_name: epictask-postgres
    environment:
      POSTGRES_DB: epictask
      POSTGRES_USER: epictask
      POSTGRES_PASSWORD: epictask
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
